### ISSUE TITLE
Message: Sql error: 'Incorrect syntax near the keyword 'order'.'

### ISSUE THREAD

**Issue by Kokulan365** [bcolpaert/Colso.Xrm.DataTransporter#34]
I copied the Fetch from Advance find and pasted in the filter, and getting the following error.

Message: Sql error: 'Incorrect syntax near the keyword 'order'.'

Message: Exception output:: System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'order'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaDa...).

If i remove the filter fetch, it works fine but i want to narrow down the list of records synced using Fetch query. Just wondering if anyone else had the same issue.

Thanks

**Comment by maeg02** [comment]
Not yet, what is the XML you posted in there?

**Comment by Jobengaru** [comment]
Hi, I do have the same issue.
The "order error" is not causing in the XML - I've deleted it in there, but the error is still there. I do not have a chance to use the filter. So it is unusable for me right now...
Regards Ferdinand

**Comment by maeg02** [comment]
> Hi, I do have the same issue.
> The "order error" is not causing in the XML - I've deleted it in there, but the error is still there. I do not have a chance to use the filter. So it is unusable for me right now...
> Regards Ferdinand

So you do not have any filter at all anymore and still get the "order error"?

**Comment by Jobengaru** [comment]
Without any filter I do get an other Error Message while using the preview...

**Comment by Jobengaru** [comment]
System.Runtime.Serialization.SerializationException: Type 'Infoman.AzureStorage.BlobStorageException' in assembly 'Infoman.Crm.Annotations, Version=1.0.830.4, Culture=neutral, PublicKeyToken=b8a18aa05801839f' is not marked as serializable.
   at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, Dictionary`2 sandboxServices, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, IPluginExecutionContext requestContext, Boolean enablePluginStackTrace, Boolean chaosFailAppDomain)
   at Microsoft.Crm.Sandbox.SandboxWorker.<>c__DisplayClass3_0.<Execute>b__0(): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #35E9172B.

**Comment by Jobengaru** [comment]
My fetch XML was like this:
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="annotation">
    <attribute name="subject" />
    <attribute name="notetext" />
    <attribute name="filename" />
    <attribute name="annotationid" />
    <attribute name="ownerid" />
    <attribute name="isdocument" />
    <attribute name="filesize" />
    <attribute name="createdon" />
    <order descending="false" attribute="createdon" />
    <link-entity name="geb_documenttemplate" from="geb_documenttemplateid" to="objectid" link-type="inner" alias="ag">
      <filter type="and">
        <condition attribute="geb_documenttemplateid" operator="not-null" />
      </filter>
    </link-entity>
  </entity>
</fetch>

**Comment by Jobengaru** [comment]
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="annotation">
    <attribute name="subject" />
    <attribute name="notetext" />
    <attribute name="filename" />
    <attribute name="annotationid" />
    <attribute name="ownerid" />
    <attribute name="isdocument" />
    <attribute name="filesize" />
    <attribute name="createdon" />
    <order descending="false" attribute="createdon" />
    <link-entity name="geb_documenttemplate" from="geb_documenttemplateid" to="objectid" link-type="inner" alias="ag">
      <filter type="and">
        <condition attribute="geb_documenttemplateid" operator="not-null" />
      </filter>
    </link-entity>
  </entity>
</fetch>

**Comment by Jobengaru** [comment]
Can you see the Fetch XML?

**Comment by Jobengaru** [comment]
![image](https://user-images.githubusercontent.com/50359989/57288726-51cb0b80-70ba-11e9-8f1f-1fdc2b9f78b5.png)

**Comment by maeg02** [comment]
well, if I add something like this:
`<link-entity name="account" from="accountid" to="objectid" link-type="inner" alias="ad">
  <filter type="and">
	<condition attribute="name" operator="like" value="%s%" />
  </filter>
</link-entity>
`
then I can do preview.

So if you can go into more details what you have done.
What was the steps that you have taken?
What input did you provide?

**Comment by Jobengaru** [comment]
Hi Markus, I'll try to get the Information for you tomorrow.
Regards,

Ferdinand

Markus Erlandsson <notifications@github.com> schrieb am Do., 9. Mai 2019,
12:50:

**Comment by LukePa1mer** [comment]
I'm also getting the same error when using the following xml:

`<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="adv_property">
    <attribute name="adv_towncity" />
    <attribute name="adv_postcode" />
    <attribute name="ownerid" />
    <attribute name="adv_addressline1" />
    <attribute name="adv_name" />
    <attribute name="adv_plotnumber" />
    <attribute name="adv_postalnumber" />
    <attribute name="adv_activetenantid" />
    <attribute name="adv_propertystatusid" />
    <attribute name="adv_blockid" />
    <attribute name="adv_propertyid" />
    <order attribute="adv_towncity" descending="false" />
    <filter type="and">
      <condition attribute="statecode" operator="eq" value="0" />
      <condition attribute="adv_addressline1" operator="like" value="Garage%" />
    </filter>
  </entity>
</fetch>`

Any ideas?

**Comment by maeg02** [comment]
> I'm also getting the same error (incorrect syntax near keyword 'order') when using the following xml:
> 
> `<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false"> <entity name="adv_property"> <attribute name="adv_towncity" /> <attribute name="adv_postcode" /> <attribute name="ownerid" /> <attribute name="adv_addressline1" /> <attribute name="adv_name" /> <attribute name="adv_plotnumber" /> <attribute name="adv_postalnumber" /> <attribute name="adv_activetenantid" /> <attribute name="adv_propertystatusid" /> <attribute name="adv_blockid" /> <attribute name="adv_propertyid" /> <order attribute="adv_towncity" descending="false" /> <filter type="and"> <condition attribute="statecode" operator="eq" value="0" /> <condition attribute="adv_addressline1" operator="like" value="Garage%" /> </filter> </entity> </fetch>`
> 
> Any ideas?

What happens if you put only the filter in this field instead, that is:
`<filter type="and"> <condition attribute="statecode" operator="eq" value="0" /> <condition attribute="adv_addressline1" operator="like" value="Garage%" /> </filter>`

**Comment by tpmeredith** [comment]
I had same issue but taking the filter out like you said above @maeg02 fixed it for me

**Comment by JFulfordMS** [comment]
Get the same error with the following Fetch.

<fetch>
  <entity name="product" >
    <all-attributes/>
    <filter>
      <condition attribute="productid" operator="eq" value="adee84a8-2165-ea11-a811-000d3a10239f" />
    </filter>
  </entity>
</fetch>

**Comment by LukePa1mer** [comment]
JFulfordMS, you only need the filter part of the query. 

Use this instead

`<filter>
      <condition attribute="productid" operator="eq" value="adee84a8-2165-ea11-a811-000d3a10239f" />
    </filter>`

> Get the same error with the following Fetch.
> 
> ```
> <fetch>
>   <entity name="product" >
>     <all-attributes/>
>     <filter>
>       <condition attribute="productid" operator="eq" value="adee84a8-2165-ea11-a811-000d3a10239f" />
>     </filter>
>   </entity>
> </fetch>
> ```

**Comment by JFulfordMS** [comment]
> JFulfordMS, you only need the filter part of the query.
> 
> Use this instead
> 
> ```
> <filter>
>       <condition attribute="productid" operator="eq" value="adee84a8-2165-ea11-a811-000d3a10239f" />
> </filter>
> ```

Awesome, thank you sir!
